/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as FailureAnalyzerRouteImport } from './routes/failure-analyzer'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AtsRouteImport } from './routes/ats'
import { Route as IndexRouteImport } from './routes/index'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const FailureAnalyzerRoute = FailureAnalyzerRouteImport.update({
  id: '/failure-analyzer',
  path: '/failure-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsRoute = AtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRoute
  '/failure-analyzer': typeof FailureAnalyzerRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRoute
  '/referrals': typeof ReferralsRoute
  '/resume': typeof ResumeRoute
  '/tracker': typeof TrackerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRoute
  '/failure-analyzer': typeof FailureAnalyzerRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRoute
  '/referrals': typeof ReferralsRoute
  '/resume': typeof ResumeRoute
  '/tracker': typeof TrackerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/dashboard': typeof DashboardRoute
  '/employer': typeof EmployerRoute
  '/failure-analyzer': typeof FailureAnalyzerRoute
  '/interview': typeof InterviewRoute
  '/jobs': typeof JobsRoute
  '/referrals': typeof ReferralsRoute
  '/resume': typeof ResumeRoute
  '/tracker': typeof TrackerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ats'
    | '/dashboard'
    | '/employer'
    | '/failure-analyzer'
    | '/interview'
    | '/jobs'
    | '/referrals'
    | '/resume'
    | '/tracker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ats'
    | '/dashboard'
    | '/employer'
    | '/failure-analyzer'
    | '/interview'
    | '/jobs'
    | '/referrals'
    | '/resume'
    | '/tracker'
  id:
    | '__root__'
    | '/'
    | '/ats'
    | '/dashboard'
    | '/employer'
    | '/failure-analyzer'
    | '/interview'
    | '/jobs'
    | '/referrals'
    | '/resume'
    | '/tracker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtsRoute: typeof AtsRoute
  DashboardRoute: typeof DashboardRoute
  EmployerRoute: typeof EmployerRoute
  FailureAnalyzerRoute: typeof FailureAnalyzerRoute
  InterviewRoute: typeof InterviewRoute
  JobsRoute: typeof JobsRoute
  ReferralsRoute: typeof ReferralsRoute
  ResumeRoute: typeof ResumeRoute
  TrackerRoute: typeof TrackerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failure-analyzer': {
      id: '/failure-analyzer'
      path: '/failure-analyzer'
      fullPath: '/failure-analyzer'
      preLoaderRoute: typeof FailureAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats': {
      id: '/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtsRoute: AtsRoute,
  DashboardRoute: DashboardRoute,
  EmployerRoute: EmployerRoute,
  FailureAnalyzerRoute: FailureAnalyzerRoute,
  InterviewRoute: InterviewRoute,
  JobsRoute: JobsRoute,
  ReferralsRoute: ReferralsRoute,
  ResumeRoute: ResumeRoute,
  TrackerRoute: TrackerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
